import { AIProvider } from './AIProvider.mjs';
import { buildReplyPrompt } from './prompts.mjs';
import { StructuredReplyParser } from './StructuredReplyParser.mjs';

export class OpenAIProvider extends AIProvider{
  constructor({apiKey,model='gpt-5.4-mini',baseUrl='https://api.openai.com/v1'}){super('openai');this.apiKey=apiKey;this.model=model;this.baseUrl=baseUrl.replace(/\/$/,'');}
  async *streamReply(input,{signal}={}){const prompt=buildReplyPrompt(input,{json:true});const schema={type:'object',additionalProperties:false,required:['answer','type','isSpeculation','relatedQuote'],properties:{answer:{type:'string'},type:{type:'string',enum:['insight','question','emotion','literary','character']},isSpeculation:{type:'boolean'},relatedQuote:{type:'string'}}};const response=await fetch(`${this.baseUrl}/responses`,{method:'POST',signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${this.apiKey}`},body:JSON.stringify({model:this.model,instructions:prompt.instructions,input:prompt.input,stream:true,store:false,max_output_tokens:700,text:{format:{type:'json_schema',name:'reading_companion_reply',strict:true,schema}}})});if(!response.ok)throw new Error(`OpenAI 返回 ${response.status}`);if(!response.body)throw new Error('OpenAI 没有返回流');const parser=new StructuredReplyParser();for await(const data of readSse(response.body)){if(data==='[DONE]')break;let event;try{event=JSON.parse(data);}catch{continue;}if(event.type==='response.output_text.delta'&&event.delta){const delta=parser.push(event.delta);if(delta)yield{type:'delta',text:delta};}if(event.type==='response.failed')throw new Error(event.response?.error?.message||'OpenAI 生成失败');}yield{type:'result',result:parser.finish()};}
}

async function* readSse(body){const reader=body.getReader();const decoder=new TextDecoder();let buffer='';try{while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);for(const line of block.split(/\r?\n/))if(line.startsWith('data:'))yield line.slice(5).trim();}}}finally{reader.releaseLock();}}
