export class StructuredReplyParser{
  buffer='';answer='';started=false;json=false;meta={type:'insight',isSpeculation:false,relatedQuote:''};
  push(chunk){this.buffer+=chunk;if(!this.started&&this.buffer.trimStart().startsWith('{'))this.json=true;if(this.json){const partial=extractPartialJsonString(this.buffer,'answer');const delta=partial.slice(this.answer.length);this.answer=partial;return delta;}if(!this.started){const match=this.buffer.match(/\r?\nANSWER:\s*\r?\n?/);if(!match)return'';const header=this.buffer.slice(0,match.index);this.meta=parseHeader(header);this.buffer=this.buffer.slice(match.index+match[0].length);this.started=true;}const delta=this.buffer;this.buffer='';this.answer+=delta;return delta;}
  finish(){if(this.json){const value=JSON.parse(this.buffer);return normalize(value);}if(!this.started){this.answer=this.buffer.trim();this.buffer='';}return{answer:this.answer.trim(),...this.meta};}
}

function parseHeader(header){const type=header.match(/TYPE:\s*([^\r\n]+)/i)?.[1]?.trim();const speculation=header.match(/SPECULATION:\s*(true|false)/i)?.[1]?.toLowerCase()==='true';const quote=header.match(/QUOTE:\s*([^\r\n]*)/i)?.[1]?.trim()||'';return{type:['insight','question','emotion','literary','character'].includes(type)?type:'insight',isSpeculation:speculation,relatedQuote:quote.slice(0,200)};}
function normalize(value){const types=['insight','question','emotion','literary','character'];return{answer:String(value.answer||'').trim(),type:types.includes(value.type)?value.type:'insight',isSpeculation:value.isSpeculation===true,relatedQuote:String(value.relatedQuote||'').trim().slice(0,200)};}
function extractPartialJsonString(raw,key){const match=new RegExp(`"${key}"\\s*:\\s*"`).exec(raw);if(!match)return'';let value='';let escaped=false;for(let i=match.index+match[0].length;i<raw.length;i++){const char=raw[i];if(escaped){if(char==='n')value+='\n';else if(char==='t')value+='\t';else if(char==='r')value+='\r';else if(char==='"'||char==='\\'||char==='/')value+=char;else if(char==='u'){const hex=raw.slice(i+1,i+5);if(hex.length<4||!/^[0-9a-f]{4}$/i.test(hex))break;value+=String.fromCharCode(parseInt(hex,16));i+=4;}escaped=false;continue;}if(char==='\\'){escaped=true;continue;}if(char==='"')break;value+=char;}return value;}
