import { useEffect, useMemo, useRef, useState } from 'react';
import ePub, { type Book, type Rendition } from 'epubjs';
import { db, type Annotation, type BookRecord, type Setting } from './db';
import { ArrowLeft, BookOpen, ChevronLeft, ChevronRight, Columns3, Expand, Eye, Feather, Library, List, Maximize2, Menu, MessageCircle, Minus, Moon, MoreHorizontal, PanelRightClose, PanelRightOpen, Plus, ScrollText, Search, Settings2, Sparkles, Sun, Upload, X } from 'lucide-react';

const defaults: Omit<Setting,'bookId'> = { fontSize: 18, lineHeight: 1.9, margin: 12, theme: 'sepia', style: 'quiet', noSpoilers: true, flow: 'paginated' };
const styleNames: Record<string,string> = { quiet:'安静陪读', snarky:'吐槽搭子', literary:'文学分析', emotion:'情绪共读' };

export default function App(){
  const [books,setBooks]=useState<BookRecord[]>([]); const [active,setActive]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const refresh=()=>db.books.orderBy('addedAt').reverse().toArray().then(setBooks);
  useEffect(()=>{ refresh().finally(()=>setLoading(false)); },[]);
  if(active) return <Reader bookId={active} onBack={()=>{setActive(null);refresh();}}/>;
  return <Home books={books} loading={loading} onOpen={setActive} onAdded={refresh}/>;
}

function Home({books,loading,onOpen,onAdded}:{books:BookRecord[];loading:boolean;onOpen:(id:string)=>void;onAdded:()=>void}){
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const input=useRef<HTMLInputElement>(null);
  async function upload(file?:File){ if(!file)return; if(!file.name.toLowerCase().endsWith('.epub')){setError('请选择 EPUB 格式的电子书。');return;} setBusy(true);setError('');
    try{ const buf=await file.arrayBuffer(); const book=ePub(buf); await book.ready; const meta=await book.loaded.metadata; let cover=''; try{cover=await book.coverUrl()||'';}catch{} const nav=await book.loaded.navigation; const id=crypto.randomUUID(); await db.books.put({id,title:meta.title||file.name.replace(/\.epub$/i,''),author:meta.creator||'未知作者',cover,file,addedAt:Date.now(),progress:0,toc:nav.toc.map((x:any)=>({label:x.label.trim(),href:x.href}))}); book.destroy(); onAdded(); }
    catch{setError('这本书没能打开，可能是文件损坏或采用了暂不支持的加密格式。');}finally{setBusy(false); if(input.current)input.current.value='';}
  }
  return <main className="home"><header className="home-head"><div className="brand"><span className="brand-mark">屿</span><div><h1>页边的阿屿</h1><p>一起读到这里，再一起往下读。</p></div></div><button className="ghost"><Search size={19}/><span>找一本书</span></button></header>
    <section className="welcome"><div><span className="eyebrow"><Feather size={14}/> AI 共读书架</span><h2>故事不必<br/>一个人读完。</h2><p>阿屿会在值得停留的地方，留下一句不吵闹的页边话。它只知道你已经读过的故事。</p></div>
      <button className="upload-card" onClick={()=>input.current?.click()} disabled={busy}><span className="upload-icon"><Upload size={25}/></span><b>{busy?'正在读这本书…':'上传一本 EPUB'}</b><small>原书仅保存在你的浏览器中</small><input ref={input} type="file" accept=".epub,application/epub+zip" hidden onChange={e=>upload(e.target.files?.[0])}/></button></section>
    {error&&<div className="error">{error}</div>}
    <section className="shelf"><div className="section-title"><div><span>我的书架</span><em>{books.length} 本</em></div>{books.length>0&&<button className="text-btn" onClick={()=>input.current?.click()}><Plus size={17}/>添加书籍</button>}</div>
      {loading?<p className="muted">正在整理书架…</p>:books.length===0?<div className="empty"><BookOpen size={28}/><p>书架还空着。挑一本想读的小说，让阿屿坐到页边来。</p></div>:<div className="book-grid">{books.map(b=><article className="book-card" key={b.id} onClick={()=>onOpen(b.id)}><div className="cover">{b.cover?<img src={b.cover}/>:<div className="cover-fallback"><span>{b.title.slice(0,8)}</span><small>{b.author}</small></div>}<button className="start">{b.progress?'继续阅读':'开始阅读'} <ChevronRight size={16}/></button></div><h3>{b.title}</h3><p>{b.author}</p><div className="progress"><i style={{width:`${b.progress}%`}}/></div><small>{b.progress?`已读 ${Math.round(b.progress)}%`:'还未开始'}</small></article>)}</div>}
    </section><footer>书页留在本地 · 阿屿只读到你读到的地方</footer></main>
}

function Reader({bookId,onBack}:{bookId:string;onBack:()=>void}){
  const host=useRef<HTMLDivElement>(null); const rendition=useRef<Rendition|null>(null); const epubBook=useRef<Book|null>(null);
  const [book,setBook]=useState<BookRecord|null>(null); const [settings,setSettings]=useState<Setting>({bookId,...defaults}); const [tocOpen,setTocOpen]=useState(false); const [asideOpen,setAsideOpen]=useState(true); const [tools,setTools]=useState(true); const [annotations,setAnnotations]=useState<Annotation[]>([]); const [selected,setSelected]=useState<{cfi:string;text:string}|null>(null); const [noteMode,setNoteMode]=useState(false); const [note,setNote]=useState(''); const [asking,setAsking]=useState(false); const [status,setStatus]=useState<'demo'|'live'>('demo'); const [chapter,setChapter]=useState(''); const [progress,setProgress]=useState(0); const [error,setError]=useState('');
  const theme=useMemo(()=>settings.theme,[settings.theme]);
  useEffect(()=>{ fetch('/api/status').then(r=>r.json()).then(x=>setStatus(x.mode)).catch(()=>setStatus('demo')); Promise.all([db.books.get(bookId),db.settings.get(bookId),db.annotations.where('bookId').equals(bookId).toArray()]).then(([b,s,a])=>{if(b)setBook(b);if(s)setSettings(s);setAnnotations(a);}); },[bookId]);
  useEffect(()=>{ if(!book||!host.current)return; let dead=false; let reader:Book|undefined; book.file.arrayBuffer().then(buf=>{if(dead)return;reader=ePub(buf);epubBook.current=reader;return reader.ready}).then(()=>{if(dead||!reader)return; const r=reader.renderTo(host.current!,{width:'100%',height:'100%',flow:settings.flow,manager:settings.flow==='scrolled-doc'?'continuous':'default',spread:'auto'}); rendition.current=r; applyTheme(r,settings); r.display(book.location||undefined); r.on('relocated',async(loc:any)=>{const pct=reader!.locations.percentageFromCfi(loc.start.cfi)*100||0;setProgress(pct); const current=book.toc?.find((x,i)=>loc.start.href.includes(x.href.split('#')[0])||book.toc?.[i+1]?.href===loc.start.href); if(current)setChapter(current.label); await db.books.update(bookId,{location:loc.start.cfi,progress:pct});}); r.on('selected',(cfi:string,contents:any)=>{const text=contents.window.getSelection()?.toString().trim(); if(text)setSelected({cfi,text});}); r.on('click',()=>setTools(x=>!x)); reader.locations.generate(1200).then(()=>{}); }); return()=>{dead=true;reader?.destroy();rendition.current=null;}; },[book]);
  useEffect(()=>{ if(rendition.current){applyTheme(rendition.current,settings); rendition.current.flow(settings.flow); db.settings.put(settings);}},[settings]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')rendition.current?.prev();if(e.key==='ArrowRight')rendition.current?.next();if(e.key==='Escape')setSelected(null);};addEventListener('keydown',key);return()=>removeEventListener('keydown',key);},[]);
  async function addNote(){if(!selected||!note.trim())return; const a:Annotation={bookId,cfi:selected.cfi,quote:selected.text,content:note.trim(),kind:'note',createdAt:Date.now(),chapter}; const id=await db.annotations.add(a); setAnnotations(x=>[...x,{...a,id}]); setNote('');setNoteMode(false);setSelected(null); rendition.current?.annotations.highlight(a.cfi,{},undefined,'user-note');}
  async function ask(action:string){if(!selected)return;setAsking(true);setError('');try{ const resp=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,selectedText:selected.text,contextBefore:selected.text,previousMemory:'',style:settings.style,noSpoilers:settings.noSpoilers,notes:annotations.filter(x=>x.kind==='note').slice(-8)})});const data=await resp.json();if(!resp.ok)throw new Error(data.error);const a:Annotation={bookId,cfi:selected.cfi,quote:selected.text,content:data.content,kind:'ai',demo:data.demo,createdAt:Date.now(),chapter};const id=await db.annotations.add(a);setAnnotations(x=>[...x,{...a,id}]);setAsideOpen(true);rendition.current?.annotations.underline(a.cfi,{},undefined,'ayu-note');setSelected(null);}catch(e:any){setError(e.message||'阿屿暂时没有回应。');}finally{setAsking(false);}}
  async function discussChapter(){const loc:any=rendition.current?.currentLocation();const cfi=loc?.start?.cfi;if(!cfi)return;setAsking(true);try{const resp=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'discuss',selectedText:`刚读完「${chapter||'这一章'}」`,contextBefore:`我们刚刚一起读完了「${chapter||'这一章'}」。请从感受、人物或猜测中选一个自然的话题开场，但不要透露后续。`,style:settings.style,noSpoilers:settings.noSpoilers,notes:annotations.slice(-8)})});const data=await resp.json();if(!resp.ok)throw new Error(data.error);const a:Annotation={bookId,cfi,quote:`读完「${chapter||'这一章'}」`,content:data.content,kind:'ai',demo:data.demo,createdAt:Date.now(),chapter};const id=await db.annotations.add(a);setAnnotations(x=>[...x,{...a,id}]);}catch(e:any){setError(e.message||'阿屿暂时没有回应。');}finally{setAsking(false);}}
  function jump(a:Annotation){rendition.current?.display(a.cfi);setSelected(null);if(innerWidth<800)setAsideOpen(false);}
  if(!book)return <div className="reader-loading">正在翻开书页…</div>;
  return <div className={`reader theme-${theme} ${tools?'':'tools-hidden'}`}>
    <header className="reader-top"><div className="top-left"><button onClick={onBack} aria-label="返回书架"><ArrowLeft/></button><button onClick={()=>setTocOpen(!tocOpen)} aria-label="目录"><List/></button><div className="reader-title"><b>{book.title}</b><span>{chapter||book.author}</span></div></div><div className="top-center"><span>阿屿目前也只读到这里</span><i/><b>{Math.round(progress)}%</b></div><div className="top-actions"><button onClick={()=>setSettings(x=>({...x,flow:x.flow==='paginated'?'scrolled-doc':'paginated'}))} title="切换翻页/滚动"><ScrollText/></button><SettingsPopover settings={settings} setSettings={setSettings}/><button onClick={()=>document.documentElement.requestFullscreen?.()} title="全屏"><Maximize2/></button><button onClick={()=>setAsideOpen(!asideOpen)} title="批注栏">{asideOpen?<PanelRightClose/>:<PanelRightOpen/>}</button></div></header>
    <div className="reader-body">
      <nav className={`toc ${tocOpen?'open':''}`}><div className="panel-head"><b>目录</b><button onClick={()=>setTocOpen(false)}><X/></button></div><div className="toc-list">{book.toc?.map((x,i)=><button key={i} className={chapter===x.label?'active':''} onClick={()=>{rendition.current?.display(x.href);setTocOpen(false)}}><span>{String(i+1).padStart(2,'0')}</span>{x.label}</button>)}</div></nav>
      <main className="page-shell"><button className="page-arrow prev" onClick={()=>rendition.current?.prev()}><ChevronLeft/></button><div ref={host} className="epub-host"/><button className="page-arrow next" onClick={()=>rendition.current?.next()}><ChevronRight/></button><div className="page-progress"><i style={{width:`${progress}%`}}/></div></main>
      <aside className={`notes ${asideOpen?'open':''}`}><div className="panel-head"><div><span className="dot"/><b>阿屿的页边批注</b></div><button onClick={()=>setAsideOpen(false)}><X/></button></div><div className="companion"><Sparkles size={16}/><span>{styleNames[settings.style]}</span><em>{status==='demo'?'演示模式':'在线陪读'}</em></div>{annotations.length===0?<div className="quiet"><Feather/><h3>先安静地读一会儿</h3><p>选中让你停下来的句子，可以问阿屿，也可以记下自己的想法。</p></div>:<div className="annotation-list">{annotations.map(a=><button key={a.id} className={`annotation ${a.kind}`} onClick={()=>jump(a)}><span className="anno-type">{a.kind==='note'?'我的想法':'阿屿'} {a.demo&&<em>演示</em>}</span><q>{a.quote}</q><p>{a.content}</p><small>{a.chapter||'本章'} · 点击回到原文</small></button>)}</div>}<button className="chapter-chat" disabled={asking} onClick={discussChapter}><MessageCircle size={17}/>{asking?'阿屿正在想…':'和阿屿聊聊这一章'}</button></aside>
    </div>
    {selected&&<div className="selection-card"><div className="selection-quote">“{selected.text.slice(0,90)}{selected.text.length>90?'…':''}”</div>{noteMode?<div className="note-editor"><textarea autoFocus placeholder="写下此刻想到的…" value={note} onChange={e=>setNote(e.target.value)}/><div><button onClick={()=>setNoteMode(false)}>取消</button><button className="primary" onClick={addNote}>保存想法</button></div></div>:<div className="selection-actions"><button disabled={asking} onClick={()=>ask('ask')}><MessageCircle/>问阿屿</button><button disabled={asking} onClick={()=>ask('explain')}><Eye/>解释这句话</button><button disabled={asking} onClick={()=>ask('psychology')}><Sparkles/>分析人物心理</button><button onClick={()=>setNoteMode(true)}><Feather/>记录我的想法</button><button className="close" onClick={()=>setSelected(null)}><X/></button></div>}{asking&&<small className="thinking">阿屿正在想，但不会往后偷看…</small>}</div>}
    {error&&<div className="toast">{error}<button onClick={()=>setError('')}><X/></button></div>}
  </div>;
}

function SettingsPopover({settings,setSettings}:{settings:Setting;setSettings:(f:(x:Setting)=>Setting)=>void}){const [open,setOpen]=useState(false);return <div className="settings-wrap"><button onClick={()=>setOpen(!open)} title="阅读设置"><Settings2/></button>{open&&<div className="settings-pop"><div className="setting-row"><span>字号</span><button onClick={()=>setSettings(x=>({...x,fontSize:Math.max(14,x.fontSize-1)}))}><Minus/></button><b>{settings.fontSize}</b><button onClick={()=>setSettings(x=>({...x,fontSize:Math.min(28,x.fontSize+1)}))}><Plus/></button></div><label>行距 <input type="range" min="1.4" max="2.4" step="0.1" value={settings.lineHeight} onChange={e=>setSettings(x=>({...x,lineHeight:+e.target.value}))}/></label><label>页边距 <input type="range" min="4" max="22" value={settings.margin} onChange={e=>setSettings(x=>({...x,margin:+e.target.value}))}/></label><div className="themes"><button className={settings.theme==='light'?'active':''} onClick={()=>setSettings(x=>({...x,theme:'light'}))}><Sun/>浅色</button><button className={settings.theme==='sepia'?'active':''} onClick={()=>setSettings(x=>({...x,theme:'sepia'}))}><BookOpen/>护眼</button><button className={settings.theme==='dark'?'active':''} onClick={()=>setSettings(x=>({...x,theme:'dark'}))}><Moon/>深色</button></div><label>陪读风格 <select value={settings.style} onChange={e=>setSettings(x=>({...x,style:e.target.value}))}>{Object.entries(styleNames).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label className="switch"><span><b>严格禁止剧透</b><small>只发送读到这里之前的内容</small></span><input type="checkbox" checked={settings.noSpoilers} onChange={e=>setSettings(x=>({...x,noSpoilers:e.target.checked}))}/><i/></label></div>}</div>}

function applyTheme(r:Rendition,s:Setting){const colors=s.theme==='dark'?{bg:'#1c1b18',text:'#d8d1c4',link:'#bca986'}:s.theme==='light'?{bg:'#faf9f5',text:'#302d28',link:'#7b6043'}:{bg:'#f4eddd',text:'#3c352b',link:'#806446'};r.themes.register('ayu',{body:{background:`${colors.bg} !important`,color:`${colors.text} !important`,'font-family':'"Noto Serif SC","Songti SC",serif !important','padding':`0 ${s.margin}% !important`,'line-height':`${s.lineHeight} !important`},p:{'font-size':`${s.fontSize}px !important`,'line-height':`${s.lineHeight} !important`,'text-align':'justify'},a:{color:`${colors.link} !important`},'::selection':{background:'#b7825644'}});r.themes.select('ayu');r.themes.fontSize(`${s.fontSize}px`);}
